apiVersion: v1
kind: Pod
metadata:
  labels:
    build: sandbox
spec:
  containers:
  - name: builder-base
    image: jenkinsxio/builder-base:0.1.275
    tty: true
    securityContext:
      privileged: true
    command:
    - cat
    volumeMounts:
    - name: socket
      mountPath: /var/run/docker.sock
  - name: golang
    image: golang:1.12
    tty: true
    command:
    - cat
  - name: nks-ci
    image: gcr.io/stackpoint-public/ci:23fb4da
    tty: true
    command:
    - cat
  volumes:
    - name: socket
      hostPath:
        path: /var/run/docker.sock
